export type AgentStatus = "live" | "beta" | "setup-required" | "planned" | "blocked"
export type AgentCategory =
  | "Marketing" | "Sales" | "Automation" | "Content" | "Commerce"
  | "Operations" | "Research" | "Creator" | "Platform"

export type Agent = {
  slug: string
  name: string
  category: AgentCategory
  status: AgentStatus
  description: string
  capabilities: string[]
  statusReason: string
  nextMilestone: string
  launchHref?: string
  internal?: boolean
}

export const statusMeta: Record<AgentStatus, { label: string; description: string; visual: string }> = {
  live: { label: "Live", description: "Passed an authenticated production run and is available to its intended users.", visual: "live" },
  beta: { label: "Beta", description: "Working in controlled production testing with restricted availability and monitoring.", visual: "beta" },
  "setup-required": { label: "Setup Required", description: "The build exists, but an integration, credential, workflow, or final production proof is still required.", visual: "development" },
  planned: { label: "Planned", description: "Approved roadmap capability; visible for planning and demand signals, not sold as working functionality.", visual: "soon" },
  blocked: { label: "Blocked", description: "Implementation is paused by a named external dependency or owner action.", visual: "blocked" },
}

export const agents: Agent[] = [
  { slug:"content-agent", name:"Content Agent", category:"Content", status:"live", description:"Creates practical marketing and business content through the protected AMS Vercel agent runtime.", capabilities:["Marketing copy","Product descriptions","Email drafts","Social content"], statusReason:"Passed an authenticated production generation through the AMS Vercel runtime. The run succeeded, saved its output, and committed the protected credit transaction.", nextMilestone:"Monitor early customer runs and keep failure/refund telemetry clean while expanding the shared runtime to additional AMS agents.", launchHref:"/content-agent" },
  { slug:"ams-fiverr-bridge", name:"AMS Fiverr Bridge", category:"Sales", status:"beta", description:"Classifies Fiverr activity and routes approved events into controlled AMS workflows.", capabilities:["Lead classification","Order-event handling","Safety gates","Workflow routing"], statusReason:"The intake and operator telemetry exist, with human approval retained for marketplace actions.", nextMilestone:"Process and verify a real permitted Fiverr event through intake, persistence, and operator review.", internal:true },
  { slug:"aspect-overmind", name:"Aspect Overmind", category:"Platform", status:"setup-required", description:"Coordinates specialized AMS agents, tools, and operator-approved actions.", capabilities:["Agent routing","Task coordination","Tool orchestration","Operator controls"], statusReason:"The orchestration foundation exists, but the connected workflow inventory currently returns zero workflows.", nextMilestone:"Synchronize the first production workflow and record a successful routed execution.", internal:true },
  { slug:"youtube-uploader-agent", name:"YouTube Uploader Agent", category:"Creator", status:"setup-required", description:"Prepares and uploads video assets through owner-authorized channels.", capabilities:["Video upload","Metadata","Thumbnail workflow","Publishing controls"], statusReason:"Prior uploader work exists, but the current production catalog has no fresh authenticated channel execution proof.", nextMilestone:"Reconnect the authorized channel and complete one controlled unlisted upload." , internal:true },
  { slug:"social-publisher-agent", name:"Social Publisher Agent", category:"Marketing", status:"setup-required", description:"Approval-first infrastructure for controlled multi-platform distribution.", capabilities:["Post validation","Approval gates","Platform routing","Publishing status"], statusReason:"The publishing design exists, but current platform credentials and end-to-end delivery are not verified.", nextMilestone:"Connect one approved channel and verify draft, approval, publish, and delivery status.", internal:true },
  { slug:"android-build-agent", name:"Android Build Agent", category:"Platform", status:"blocked", description:"Build automation for Android packaging and Google Play release workflows.", capabilities:["APK builds","AAB builds","Release assets","Build automation"], statusReason:"Android CI has passed, but the Google Play track remains blocked and its draft branch is not production-reconciled.", nextMilestone:"Resolve Play Console access, reconcile the Android branch with main, then produce and install-test a signed release candidate." },
  { slug:"lead-magnet-agent", name:"Lead Magnet Agent", category:"Marketing", status:"beta", description:"Creates useful conversion assets from a customer-defined problem, audience, and desired outcome through the verified AMS content runtime.", capabilities:["Lead magnets","Offer alignment","Conversion assets","Campaign support"], statusReason:"A mobile-first customer workflow is connected to the verified Content Agent execution path with protected credits and draft-only output. It has not yet completed its own authenticated production generation.", nextMilestone:"Complete one authenticated production lead-magnet generation, verify the saved run and committed credit, then promote this specialist workflow to Live.", launchHref:"/lead-magnet-agent" },
  { slug:"email-campaign-agent", name:"Email Campaign Agent", category:"Marketing", status:"planned", description:"Builds campaign structure and audience-aware email sequences for human-reviewed delivery.", capabilities:["Campaign planning","Email sequences","Audience messaging","Delivery handoff"], statusReason:"Cataloged and approved; delivery provider and workflow are not connected.", nextMilestone:"Build the sequence generator, approval gate, and one provider handoff test." },
  { slug:"nurture-agent", name:"Nurture Agent", category:"Marketing", status:"planned", description:"Builds structured prospect and customer nurture sequences.", capabilities:["Follow-up sequences","Lifecycle messaging","Lead nurture","Retention support"], statusReason:"Cataloged and approved, but no lifecycle trigger or delivery workflow is connected.", nextMilestone:"Define lifecycle events and test one consent-aware nurture sequence." },
  { slug:"outreach-agent", name:"Outreach Agent", category:"Sales", status:"planned", description:"Supports qualification, positioning, and human-reviewed prospect communication.", capabilities:["Lead qualification","Offer positioning","Outreach drafts","Follow-up support"], statusReason:"Cataloged and approved; prospect source, compliance rules, and sending path are not connected.", nextMilestone:"Implement qualification, approval, suppression, and a controlled draft-only test." },
  { slug:"sales-agent", name:"Sales Agent", category:"Sales", status:"planned", description:"Supports discovery, qualification, recommendations, and next-step routing.", capabilities:["Discovery","Qualification","Recommendations","Handoff routing"], statusReason:"Cataloged and approved; CRM state and a verified handoff are not connected.", nextMilestone:"Define the sales state model and verify one qualified human handoff." },
  { slug:"marketing-audit-agent", name:"Marketing Audit Agent", category:"Marketing", status:"beta", description:"Turns business inputs into a structured marketing assessment and action plan.", capabilities:["Marketing review","Gap analysis","Priority actions","Growth planning"], statusReason:"The $49 public checkout, native AMS fulfillment, durable result storage, Stripe-verified result access, and customer result page are deployed. A fresh real paid production fulfillment has not yet been re-verified after the native migration.", nextMilestone:"Complete the first fresh real paid production audit and verify checkout, signed webhook, durable native result, customer retrieval, and replay/idempotency before promoting this agent to Live.", launchHref:"/quick-marketing-audit" },
  { slug:"analytics-agent", name:"Analytics Agent", category:"Operations", status:"planned", description:"Interprets authorized business data and surfaces actionable insights.", capabilities:["Data analysis","Reporting","Trend detection","Recommendations"], statusReason:"Cataloged and approved; no customer data connector or verified analysis run is attached.", nextMilestone:"Connect one scoped dataset and validate a source-backed report." },
  { slug:"automation-builder", name:"Automation Builder", category:"Automation", status:"planned", description:"Maps repetitive processes into controlled automations.", capabilities:["Process mapping","Workflow design","Trigger planning","Integration logic"], statusReason:"Cataloged and approved; workflow generation and deployment controls are not built.", nextMilestone:"Generate, review, and safely deploy one test workflow." },
  { slug:"n8n-automation-agent", name:"n8n Automation Agent", category:"Automation", status:"blocked", description:"Designs, reviews, and improves n8n-based business workflows without making n8n a requirement for AMS core uptime or paid fulfillment.", capabilities:["n8n workflows","Webhook design","Integration planning","Failure-path review"], statusReason:"The prior n8n Cloud trial is no longer available, so the cloud worker cannot currently execute workflows. AMS website uptime and the native Quick Audit revenue path no longer depend on it.", nextMilestone:"Choose a specific workflow that still benefits from n8n, run it on self-hosted Community Edition or migrate it into AMS-native code, and record one successful isolated execution." },
  { slug:"seo-agent", name:"SEO Agent", category:"Marketing", status:"planned", description:"Creates structured optimization recommendations and content plans.", capabilities:["SEO review","Keyword planning","Content briefs","Optimization guidance"], statusReason:"Cataloged and approved; live search data and an execution workflow are not connected.", nextMilestone:"Connect an approved data source and validate one site audit." },
  { slug:"affiliate-marketing-agent", name:"Affiliate Marketing Agent", category:"Marketing", status:"planned", description:"Supports affiliate campaign structure, offer positioning, and promotional workflows.", capabilities:["Affiliate campaigns","Offer positioning","Content support","Tracking plans"], statusReason:"Cataloged and approved; tracking, attribution, and partner workflows are not connected.", nextMilestone:"Define compliant attribution and verify one partner campaign flow." },
  { slug:"shopify-agent", name:"Shopify Agent", category:"Commerce", status:"planned", description:"Supports Shopify catalog, merchandising, and store workflows.", capabilities:["Catalog support","Store workflows","Merchandising","Automation planning"], statusReason:"Cataloged and approved; no current Shopify store authorization is attached.", nextMilestone:"Connect the owner-authorized store and verify one reversible catalog update." },
  { slug:"product-creator-agent", name:"Product Creator Agent", category:"Commerce", status:"planned", description:"Turns concepts into structured digital or commerce-ready offers.", capabilities:["Product concepts","Offer packaging","Listing support","Launch assets"], statusReason:"Cataloged and approved; creation, QA, and commerce handoff are not implemented.", nextMilestone:"Build and QA one complete offer package." },
  { slug:"video-agent", name:"Video Agent", category:"Creator", status:"planned", description:"Supports scripting, metadata, production handoff, and publishing preparation.", capabilities:["Scripts","Metadata","Production handoff","Publishing prep"], statusReason:"Cataloged and approved; rendering and publishing paths are not connected in production.", nextMilestone:"Generate and render one approved test video package." },
  { slug:"twitch-watcher-agent", name:"Twitch Watcher Agent", category:"Creator", status:"planned", description:"Monitors streams for summaries, clip opportunities, and creator alerts.", capabilities:["Stream monitoring","Summaries","Clip discovery","Creator alerts"], statusReason:"Cataloged and approved; Twitch authorization and live event processing are not connected.", nextMilestone:"Connect one authorized channel and verify a live-event-to-summary run." },
  { slug:"customer-support-agent", name:"Customer Support Agent", category:"Operations", status:"planned", description:"Handles triage, knowledge-guided response drafting, and human escalation.", capabilities:["Triage","Response drafting","Knowledge lookup","Escalation"], statusReason:"Cataloged and approved; knowledge base, ticket source, and escalation path are not connected.", nextMilestone:"Connect a scoped knowledge source and validate one escalated support case." },
  { slug:"technical-support-agent", name:"Technical Support Agent", category:"Operations", status:"planned", description:"Provides structured troubleshooting and operator-approved remediation guidance.", capabilities:["Issue triage","Troubleshooting","Diagnostics","Escalation"], statusReason:"Cataloged and approved; diagnostic scope and support workflow are not implemented.", nextMilestone:"Define safe diagnostic boundaries and validate one test incident." },
  { slug:"notifier-agent", name:"Notifier Agent", category:"Operations", status:"planned", description:"Routes important business events to the right channel and operator.", capabilities:["Event alerts","Routing rules","Escalations","Delivery status"], statusReason:"Cataloged and approved; event subscriptions and delivery verification are not connected.", nextMilestone:"Connect one event source and prove delivery plus failure handling." },
  { slug:"slack-agent", name:"Slack Agent", category:"Operations", status:"planned", description:"Supports summaries, alerts, structured commands, and approved operational actions.", capabilities:["Slack summaries","Alerts","Commands","Operational handoffs"], statusReason:"Cataloged and approved; the production Slack workspace authorization is not verified.", nextMilestone:"Authorize a test workspace and verify one read-only command." },
  { slug:"telegram-agent", name:"Telegram Agent", category:"Operations", status:"planned", description:"Supports Telegram-triggered workflows, notifications, and controlled commands.", capabilities:["Telegram triggers","Notifications","Workflow handoff","Command routing"], statusReason:"Cataloged and approved; the current bot-to-production route is not verified.", nextMilestone:"Verify one authenticated trigger and notification round trip." },
  { slug:"web-scraper-agent", name:"Web Scraper Agent", category:"Research", status:"planned", description:"Collects permitted public web information into structured business inputs.", capabilities:["Public web research","Extraction","Normalization","Research handoff"], statusReason:"Cataloged and approved; policy controls and a production extraction workflow are not attached.", nextMilestone:"Define allowed sources and validate one compliant extraction." },
  { slug:"research-agent", name:"Research Agent", category:"Research", status:"planned", description:"Gathers evidence, compares sources, and creates source-aware briefs.", capabilities:["Research","Comparison","Synthesis","Source briefs"], statusReason:"Cataloged and approved; source retrieval and citation validation are not productized.", nextMilestone:"Build and validate one source-backed research brief." },
  { slug:"reverse-engineering-intelligence-agent", name:"Reverse-Engineering Intelligence Agent", category:"Research", status:"planned", description:"Monitors public releases, changelogs, and implementation patterns.", capabilities:["Release monitoring","Changelog review","Pattern analysis","Improvement briefs"], statusReason:"Cataloged and approved; monitoring sources and review controls are not configured.", nextMilestone:"Connect permitted public sources and validate one change brief." },
  { slug:"agi-research-bot", name:"AGI Research Bot", category:"Research", status:"planned", description:"Tracks AI developments and organizes findings for AMS operators.", capabilities:["AI research","Trend monitoring","Briefing","Knowledge organization"], statusReason:"Cataloged and approved; scheduled source monitoring is not connected.", nextMilestone:"Define authoritative sources and validate one scheduled briefing." },
  { slug:"console-builder", name:"Console Builder", category:"Platform", status:"planned", description:"Generates controlled internal dashboards and business interfaces.", capabilities:["Dashboard planning","UI scaffolding","Operator tools","System views"], statusReason:"Cataloged and approved; safe generation and deployment controls are not implemented.", nextMilestone:"Generate, review, and preview one isolated operator dashboard." },
  { slug:"meme-to-agent", name:"Meme-to-Agent", category:"Platform", status:"planned", description:"Turns structured creative prompts into safe, scoped agent prototypes.", capabilities:["Concept intake","Agent scoping","Prototype planning","Safety boundaries"], statusReason:"Experimental concept only; no production execution route exists.", nextMilestone:"Define acceptance criteria and build one sandboxed prototype." },
  { slug:"agent-battle-arena", name:"Agent Battle Arena", category:"Platform", status:"planned", description:"Compares agent outputs against defined quality and task criteria.", capabilities:["Agent comparison","Quality scoring","Evaluation runs","Benchmark views"], statusReason:"Experimental internal concept; evaluation datasets and scoring controls are not implemented.", nextMilestone:"Create a fixed evaluation set and compare two sandboxed agents.", internal:true },
]

export function getAgent(slug: string) {
  return agents.find((agent) => agent.slug === slug)
}

export const agentStatusCounts = agents.reduce<Record<AgentStatus, number>>(
  (counts, agent) => ({ ...counts, [agent.status]: counts[agent.status] + 1 }),
  { live: 0, beta: 0, "setup-required": 0, planned: 0, blocked: 0 },
)
